[package]
name = "inl"
version = "0.1.0"
authors = ["Nerijus Arlauskas <nercury@gmail.com>"]
build = "build.rs"

[lib]
name = "inl"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"

[dependencies.egli]
path = "../../egli"

[build-dependencies]
rusty-cheddar = "0.3.0"
